### ISSUE TITLE
Error when calling client$getCollaboration function

### ISSUE THREAD

**Issue by pedro-cmat** [IKNL/vtg#19]
Hi,
Just noticed what it seems like a bug when calling the function ```client$getCollaborations()```. 
It seems that the [last line](https://github.com/IKNL/vtg/blob/377476dea37ef4617cb8ae28324442355a85d765/R/client.R#L150) ```collaborations <- data.frame(collaborations)``` is not able to correctly parse the collaboration list previously aggregated.
In case of two collaborations with different number of organisations, it results in the following error: `arguments imply differing number of rows: 1, 3, 2`.

**Comment by frankcorneliusmartin** [comment]
Error should be gone. Unfortunately its not a `dataframe` type anymore, as I have very limited R exp. It returns a list in which each element represents a collaboration and 3 keys: `id`, `name` and `organizations`.
Feel free to re-open if this poses an issue.
